version: "3.7"
services:
  postgres:
    image: postgres
#    command: [ "postgres", "-c", "log_statement=all" ]
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_PASSWORD=bob